# Generated by Django 4.2.4 on 2023-09-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_alter_comment_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='models_app/images'),
        ),
    ]
