# Generated by Django 4.2.4 on 2023-09-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_alter_photo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='mod_status',
            field=models.CharField(blank=True, choices=[('М', 'на модерации'), ('О', 'одобрено'), ('У', 'на удалении')], default='на модерации', max_length=50),
        ),
    ]
