# Generated by Django 4.2.4 on 2023-09-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0012_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
