# Generated by Django 4.2.4 on 2023-09-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0014_alter_photo_author_alter_voice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='models_app.photo'),
        ),
    ]
