# Generated by Django 4.2.4 on 2023-09-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0014_alter_photo_author_alter_voice_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voice",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="voice", to="models_app.photo"
            ),
        ),
    ]
