# Generated by Django 4.2.4 on 2023-09-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0016_alter_comment_reply_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='models_app.comment', verbose_name='replies'),
        ),
    ]
