# Generated by Django 4.2.4 on 2023-09-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0018_alter_comment_reply_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="models_app.photo"
            ),
        ),
    ]
