# Generated by Django 4.2.4 on 2023-09-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0020_alter_photo_options_remove_comment_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photo/images'),
        ),
    ]
