# Generated by Django 4.2.4 on 2023-09-25 10:34

from django.db import migrations, models
import models_app.models.photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0021_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=models_app.models.photo.models.user_directory_path),
        ),
    ]
