# Generated by Django 4.2.5 on 2023-09-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0024_photo_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voice',
            constraint=models.UniqueConstraint(fields=('photo', 'user'), name='unique_voice'),
        ),
    ]
