# Generated by Django 4.2.5 on 2023-10-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0026_photo_is_deleted_voice_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
    ]
