# Generated by Django 4.2.5 on 2023-10-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0027_remove_photo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
