# Generated by Django 4.2.5 on 2023-10-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0028_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
