# Generated by Django 4.2.5 on 2023-10-17 11:17

from django.db import migrations, models
import models_app.signals


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0032_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=models_app.signals.uploaded_file_path),
        ),
    ]
