# Generated by Django 4.2.5 on 2023-10-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0033_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-pub_date', 'title'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
