# Generated by Django 4.2.6 on 2023-10-24 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0035_remove_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="models_app.comment",
                verbose_name="Ответ",
            ),
        ),
    ]
