# Generated by Django 5.0.3 on 2024-04-03 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0040_alter_comment_comment_id_alter_comment_comment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="comment_type",
        ),
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="models_app.comment",
                verbose_name="Ответ",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="models_app.photo",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
