# Generated by Django 5.0.4 on 2024-04-12 16:56

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0041_remove_comment_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='state',
            field=django_fsm.FSMField(blank=True, choices=[('На модерации', 'На модерации'), ('Одобрено', 'Одобрено'), ('Отклонено', 'Отклонено'), ('На удалении', 'На удалении')], default=('На модерации', 'На модерации'), max_length=50, null=True),
        ),
    ]
