# Generated by Django 5.0.4 on 2024-04-16 09:10

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0043_alter_photo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='state',
            field=django_fsm.FSMField(choices=[('На модерации', 'На модерации'), ('Одобрено', 'Одобрено'), ('Отклонено', 'Отклонено'), ('На удалении', 'На удалении')], default='На модерации', max_length=50),
        ),
    ]
