# Generated by Django 5.0.2 on 2024-05-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0046_alter_photo_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="pub_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
