# Generated by Django 4.1 on 2024-06-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0047_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
    ]
