# Generated by Django 5.0.6 on 2024-06-02 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0048_alter_photo_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='models_app.photo'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='voices', to=settings.AUTH_USER_MODEL),
        ),
    ]
