# Generated by Django 4.1 on 2024-06-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0048_alter_photo_pub_date"),
        ("models_app", "0049_alter_voice_photo_alter_voice_user"),
    ]

    operations = []
